[workspace]
authors = ["Tong <t1871038859@gmail.com>"]
channels = ["conda-forge"]
name = "fullstack-project"
platforms = ["win-64"]
version = "0.1.0"

[tasks]


[feature.btest.dependencies]
pytest = "*"
pytest-mock = ">=3.14.1,<4"
faker = ">=37.3.0,<38"
httpx = ">=0.28.1,<0.29"
ipython = ">=9.3.0,<10"
ipykernel = ">=6.29.5,<7"

[feature.backend.dependencies]
python = ">=3.13.3,<3.14"
websockets = ">=15.0.1,<16"
aiomysql = ">=0.2.0,<0.3"
sqlmodel = ">=0.0.24,<0.0.25"
sqlalchemy = ">=2.0.41,<3"
python-json-logger = ">=2.0.7,<3"
fastapi = ">=0.115.12,<0.116"

[feature.backend.tasks]
start = { cmd = "fastapi dev main.py", description = "fastapi dev main.py" }

[feature.backend.pypi-dependencies]
pydantic-settings = ">=2.9.1, <3"
redis = ">=6.2.0, <7"
pymongo = ">=4.13.0, <5"

[feature.frontend.dependencies]
pnpm = ">=10.11.1,<11"
nodejs = ">=22.13.0,<22.14"

[environments]
prod = { features = ["backend"], no-default-feature = true }
dev = ["btest", "backend","frontend"]
webui = ["frontend"]

