[workspace]
authors = ["Tong <t1871038859@gmail.com>"]
channels = ["conda-forge"]
name = "blog"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pytest = ">=8.3.5,<9"
fastapi = ">=0.115.12,<0.116"
uvicorn = ">=0.34.2,<0.35"
sqlmodel = ">=0.0.24,<0.0.25"
pymysql = ">=1.1.1,<2"
pyjwt = ">=2.10.1,<3"
passlib = ">=1.7.4,<2"

[pypi-dependencies]
pydantic-settings = ">=2.9.1, <3"
