[workspace]
authors = ["Tong <t1871038859@gmail.com>"]
channels = ["conda-forge"]
name = "websockets"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
fastapi = ">=0.115.12,<0.116"
websockets = ">=15.0.1,<16"
aiomysql = ">=0.2.0,<0.3"
aioredis = ">=2.0.1,<3"
sqlmodel = ">=0.0.24,<0.0.25"
sqlalchemy = ">=2.0.41,<3"
ipykernel = ">=6.29.5,<7"
python-json-logger = ">=2.0.7,<3"
pytest = ">=8.4.0,<9"
faker = ">=37.3.0,<38"
pytest-mock = ">=3.14.1,<4"
httpx = ">=0.28.1,<0.29"

[environments]
testpixi = { solve-group = "default" }
